#! /usr/bin/bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
	gsettings set org.gnome.desktop.background primary-color '#000000'

	printf "\n\nDone, changed background color to black.\n"

	exit # 0
}

printf "\nStarting changing background colors..."
printf "\nPress Ctrl+C to stop the script.\n\n"

sleep 1.5 

nums=({-1..255..64}) # ($(seq -1 64 255))
 
nums[0]=0

while true; do
	for red in ${nums[@]}; do
		for green in ${nums[@]}; do
			for blue in ${nums[@]}; do
				color="#$(printf "%02x%02x%02x\n" $red $green $blue)"	
				gsettings set org.gnome.desktop.background primary-color $color
				sleep 0.25
				echo "Changed background color to $color"
			done
		done 
	done
done

