#! /usr/bin/env bash

background_uri=$(gsettings get org.gnome.desktop.background picture-uri)
background_color=$(gsettings get org.gnome.desktop.background primary-color)

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
    printf "\n\nDone, changed background "

    if [ $background_uri ]; then
        gsettings set org.gnome.desktop.background picture-uri $background_uri
        printf "to the image which was set" 
    elif [ $background_color ]; then
        gsettings set org.gnome.desktop.background primary-color $background_color
        printf "color to the color which was set"
    else
        gsettings set org.gnome.desktop.background primary-color '#000000'
        printf "color to black"
    fi

    printf ".\n"

	exit # 0
}

printf "\nStarting changing background colors..."
printf "\nPress Ctrl+C to stop the script."

if [ $background_uri ]; then
    gsettings set org.gnome.desktop.background picture-uri ''
    printf "\nBackground set to empty image (black color)\n\n"
fi

sleep 1.5 

nums=({-1..255..64}) # ($(seq -1 64 255))
 
nums[0]=0

while true; do
	for red in ${nums[@]}; do
		for green in ${nums[@]}; do
			for blue in ${nums[@]}; do
				color="#$(printf "%02x%02x%02x\n" $red $green $blue)"	
				gsettings set org.gnome.desktop.background primary-color $color
				sleep 0.25
				echo "Changed background color to $color"
			done
		done 
	done
done

